### PR TITLE
Rebar-ify the JavaErlang application

### PR DESCRIPTION
**Pull request by norton**
Rebar-ify the JavaErlang application.

See README.md for instructions on how to build, to eunit, and to generate edocs via edown.

I did not try to check any other tests besides the eunit ones.

### CODE REVIEW

**Comment by norton** [comment]
I corrected the enable_gc implementation to behave as a noop if the platform does not support NIFs.  I'm a little unclear if this is the desired behavior for this option or not.

**Comment by fredlund** [comment]
Thanks for the code! I will take a look at the code asap. Having enable_gc as a noop if the platform has no NIF support should be ok.

**Comment by fredlund** [comment]
Looks fine, a couple of questions/doubts first though, since I am not so used to packaging with rebar. 

#1. I guess one would want to define an application too (a pure library application for sure), or is this discouraged nowadays? (I am happy to do it, just want your opinion)

#2. The Makefile should be redone but still offer the possibility to install JavaErlang somewhere, right? (I am happy to do it).

#3. The line -compile({nowarn_deprecated_function, [{erlang, now, 0}]}).
in java.erl actually generates a warning (thus preventing compilation) on some erlang versions, as the compiler ***warns*** about erlang:now NOT being deprecated. Painful, yes.

#4. It would be nice with an update to the INSTALL file for how to build the tool and documentation using rebar.

**Comment by norton** [comment]
#1. Yes, I agree.  I also wonder if java_proxy:start() should be started by this new application's supervisor.

#2. Yes, fine.

#3. I will take a look and see if there is a better way to handle this.

#4. Yes, fine ... I can update the INSTALL file.

#5. Can you also see if the TODO file needs updating.

**Comment by norton** [comment]
@fredlund I tested, committed and pushed changes to address most of these items.

- I did not change the INSTALL nor address the Makefile recipe to install JavaErlang.  Please take care of this item.
- FYI.  edown does not work yet with 18 ... please use 17.5 or earlier.
- FYI.  The latest version of rebar3 has changed since my previous commits and rebar3 eunit does not work now.   Something was broken? in one of these commits (git log 123b0ea..0537a06). I will submit an issue for rebar3.

```
$ git checkout 123b0ea
$ make
$ ./bootstrap/bootstrap
$ rebar3 -v
rebar 3.0.0-alpha-4 on Erlang/OTP 17 Erts 6.4
```

**Comment by fredlund** [comment]
- Ok, I will change the INSTALL and generate a Makefile. Probably not before monday though, and I will not pull the changes until then.

- Edown does not seem to work from rebar3 under R16B either:

./rebar3 edoc
===> Running edoc for java_erlang
edoc: error in doclet 'edown_doclet': {'EXIT',{undef,[{edown_doclet,run,[{doclet_gen,[{java_resource,'',[106,97,118,97|...]

No big deal, I will include support for generating the documentation from the Makefile too. 

- On the other hand rebar3 eunit does work here.

**Pull request merged**
